[package]
name = "fahren_cel_convert"
version = "0.1.0"
authors = ["Daniel Coats <daniel.e.coats@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
